import { AdminMenu } from '../../interfaces/core/admin-menu.interface';
import { environment } from '../../../environments/environment';


const ALL_MENUS: AdminMenu[] = [
  {
    id: 0,
    name: 'Dashboard',
    hasSubMenu: false,
    routerLink: 'dashboard',
    icon: 'space_dashboard',
    subMenus: [],
  },
  {
    id: 1,
    name: 'Orders',
    hasSubMenu: false,
    routerLink: 'order/all-order',
    icon: 'reorder',
    subMenus: [],
  },
  // {
  //   id: 1,
  //   name: 'Incomplete Orders',
  //   hasSubMenu: false,
  //   routerLink: 'order/all-incomplete-order',
  //   icon: 'reorder',
  //   subMenus: [],
  // },
  {
    id: 2,
    name: 'Products',
    hasSubMenu: false,
    routerLink: 'product/all-product',
    icon: 'inventory_2',
    subMenus: [],
  },
  {
    id: 3,
    name: 'Settings',
    hasSubMenu: false,
    routerLink: 'settings/all-settings',
    icon: 'settings',
    subMenus: [],
  },
  {
    id: 4,
    name: 'Customization',
    hasSubMenu: true,
    routerLink: null,
    icon: 'tune',
    subMenus: [
      {
        id: 2,
        name: 'Carousel',
        hasSubMenu: true,
        routerLink: 'customization/all-carousel',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: 'Banner',
        hasSubMenu: true,
        routerLink: 'customization/all-banner',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'PopUp',
        hasSubMenu: true,
        routerLink: 'customization/all-popup',
        icon: 'arrow_right',
      },
      {
        id: 5,
        name: 'Website Information',
        hasSubMenu: true,
        routerLink: 'customization/website-information',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Theme View',
        hasSubMenu: true,
        routerLink: 'customization/theme-view',
        icon: 'arrow_right',
      },
      // {
      //   id: 7,
      //   name: 'Themes',
      //   hasSubMenu: false,
      //   routerLink: 'customization/themes',
      //   icon: 'arrow_right',
      // },
      // {
      //   id: 8,
      //   name: 'Page View',
      //   hasSubMenu: true,
      //   routerLink: 'customization/page-view',
      //   icon: 'arrow_right',
      // },
    ],
  },
  {
    id: 5,
    name: 'Catalog',
    hasSubMenu: true,
    routerLink: null,
    icon: 'category',
    subMenus: [
      {
        id: 1,
        name: 'Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-category',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: ' Sub Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-sub-category',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: ' Child Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-child-category',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'Brand',
        hasSubMenu: true,
        routerLink: 'catalog/all-brand',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Tags',
        hasSubMenu: true,
        routerLink: 'catalog/all-tag',
        icon: 'arrow_right',
      },
      // {
      //   id: 7,
      //   name: 'Skin Type',
      //   hasSubMenu: true,
      //   routerLink: 'catalog/all-skin-type',
      //   icon: 'arrow_right',
      // },
      // {
      //   id: 8,
      //   name: 'Skin Concern',
      //   hasSubMenu: true,
      //   routerLink: 'catalog/all-skin-concern',
      //   icon: 'arrow_right',
      // },
    ],
  },
  {
    id: 577,
    name: 'Landing page',
    hasSubMenu: true,
    routerLink: null,
    icon: 'web',
    subMenus: [
      {
        id: 1,
        name: 'Customizable Landing page',
        hasSubMenu: true,
        routerLink: 'landing-page/all-customizable-landing-page',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: 'Ready Landing page',
        hasSubMenu: true,
        routerLink: 'landing-page/all-fixed-landing-page',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: 'Ready Landing page2',
        hasSubMenu: true,
        routerLink: 'landing-page/all-ready-landing-page',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 6,
    name: 'Review',
    hasSubMenu: false,
    routerLink: 'review',
    icon: 'reviews',
    subMenus: [],
  },

  {
    id: 7,
    name: 'Customer',
    hasSubMenu: false,
    routerLink: 'users/all-users',
    icon: 'group',
    subMenus: [],
  },
  {
    id: 77,
    name: 'Coupon',
    hasSubMenu: false,
    routerLink: 'coupon/all-coupon',
    icon: 'payments',
    subMenus: [],
  },

  {
    id: 8,
    name: 'Gallery',
    hasSubMenu: false,
    routerLink: 'my-gallery',
    icon: 'insert_photo',
    subMenus: []
  },
  {
    id: 9,
    name: 'Additional Pages',
    hasSubMenu: false,
    routerLink: 'additional-pages/page-list',
    icon: 'pages',
    subMenus: [],
  },
  {
    id: 222,
    name: 'Seo Pages',
    hasSubMenu: false,
    routerLink: 'seo-page/all-seo-page',
    icon: 'traffic',
    subMenus: [],
  },

  // {
  //   id: 117,
  //   name: 'Affiliate',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All affiliate',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/all-affiliate',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Affiliate product',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate-product/all-affiliate-product',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'Affiliate request',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/affiliate-request',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 4,
  //       name: 'All approved affiliate',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/all-approved-affiliate',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 5,
  //       name: 'All affiliate payment request',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/affiliate-payment-request',
  //       icon: 'arrow_right',
  //     },


  //   ],
  // },
  // {
  //   id: 19,
  //   name: 'Tutorial Page',
  //   hasSubMenu: false,
  //   routerLink: 'tutorial',
  //   icon: 'videocam',
  //   subMenus: [],
  // },
  // {
  //   id: 117,
  //   name: 'Subscription',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Subscription',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/all-subscription',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Subscription Report',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/subscription-report',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'My Subscription',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/my-subscription',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 317,
  //   name: 'Manager',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Log Manager',
  //       hasSubMenu: true,
  //       routerLink: 'manager/all-log',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'All Trash Manager',
  //       hasSubMenu: true,
  //       routerLink: 'manager/all-trash',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  {
    id: 318,
    name: 'Expense',
    hasSubMenu: true,
    routerLink: null,
    icon: 'assessment',
    subMenus: [
      {
        id: 1,
        name: 'All Expense',
        hasSubMenu: true,
        routerLink: 'expense/all-expense',
        icon: 'arrow_right',
      },
      {
        id: 1,
        name: 'All category',
        hasSubMenu: true,
        routerLink: 'expense/all-category',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 319,
    name: 'Income',
    hasSubMenu: true,
    routerLink: null,
    icon: 'trending_up',
    subMenus: [
      {
        id: 1,
        name: 'All Income',
        hasSubMenu: true,
        routerLink: 'income/all-income',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: 'All category',
        hasSubMenu: true,
        routerLink: 'income/all-category',
        icon: 'arrow_right',
      },
    ],
  },

  // {
  //   id: 3218,
  //   name: 'User Notification',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Notification',
  //       hasSubMenu: true,
  //       routerLink: 'fake-notification/all-notification',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  {
    id: 600,
    name: 'Accounts',
    hasSubMenu: true,
    routerLink: null,
    icon: 'account_balance',
    subMenus: [
      {
        id: 15,
        name: 'Bank Account List',
        hasSubMenu: true,
        routerLink: 'pos/accounts/bank-account-list',
        icon: 'arrow_right',
      },
      {
        id: 16,
        name: 'Add Bank Account',
        hasSubMenu: true,
        routerLink: 'pos/accounts/add-bank-account',
        icon: 'arrow_right',
      },
      {
        id: 17,
        name: 'Cash Transaction List',
        hasSubMenu: true,
        routerLink: 'pos/accounts/cash-transaction-list',
        icon: 'arrow_right',
      },
      {
        id: 18,
        name: 'Add Cash Transaction',
        hasSubMenu: true,
        routerLink: 'pos/accounts/add-cash-transaction',
        icon: 'arrow_right',
      },
      {
        id: 19,
        name: 'Accounts Ledger',
        hasSubMenu: true,
        routerLink: 'pos/accounts/accounts-ledger',
        icon: 'arrow_right',
      },
      {
        id: 20,
        name: 'Day Close',
        hasSubMenu: true,
        routerLink: 'pos/accounts/day-close',
        icon: 'arrow_right',
      },

      {
        id: 21,
        name: 'Balance Sheet',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/balance-sheet',
        icon: 'arrow_right',
      },
      {
        id: 22,
        name: 'Profit & Loss',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/profit-loss',
        icon: 'arrow_right',
      },
      {
        id: 23,
        name: 'Tax Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/tax-report',
        icon: 'arrow_right',
      },
      {
        id: 39,
        name: 'Sales Record',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/sales-record',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 13,
    name: 'Pos',
    hasSubMenu: true,
    routerLink: null,
    icon: 'point_of_sale',
    subMenus: [
      {
        id: 99,
        name: 'POS Dashboard',
        hasSubMenu: true,
        routerLink: 'pos/dashboard',
        icon: 'dashboard',
      },
      {
        id: 100,
        name: 'Repair',
        hasSubMenu: true,
        routerLink: null,
        icon: 'build',
        subMenus: [
          {
            id: 1,
            name: 'Repair List',
            hasSubMenu: true,
            routerLink: 'repair/repair-list',
            icon: 'arrow_right',
          },
          {
            id: 2,
            name: 'Add Repair',
            hasSubMenu: true,
            routerLink: 'repair/add-repair',
            icon: 'arrow_right',
          },
          {
            id: 3,
            name: 'Model',
            hasSubMenu: true,
            routerLink: 'repair/model-list',
            icon: 'arrow_right',
          },
          {
            id: 4,
            name: 'Problem',
            hasSubMenu: true,
            routerLink: 'repair/problem-list',
            icon: 'arrow_right',
          },
          {
            id: 5,
            name: 'Technician Report',
            hasSubMenu: true,
            routerLink: 'repair/technician-report',
            icon: 'arrow_right',
          },
          {
            id: 6,
            name: 'Technician List',
            hasSubMenu: true,
            routerLink: 'repair/technician-list',
            icon: 'arrow_right',
          },
          {
            id: 7,
            name: 'Add Technician',
            hasSubMenu: true,
            routerLink: 'repair/add-technician',
            icon: 'arrow_right',
          },
        ],
      },
      {
        id: 200,
        name: 'Sales',
        hasSubMenu: true,
        routerLink: null,
        icon: 'shopping_cart',
        subMenus: [
          {
            id: 5,
            name: 'Sales List',
            hasSubMenu: true,
            routerLink: 'pos/sales/sale-list',
            icon: 'arrow_right',
          },
          {
            id: 6,
            name: 'New Sale',
            hasSubMenu: true,
            routerLink: 'pos/sales/new-sales',
            icon: 'arrow_right',
          },
          {
            id: 7,
            name: 'Sales Return',
            hasSubMenu: true,
            routerLink: 'pos/sales/new-sales-return',
            icon: 'arrow_right',
          },
          {
            id: 8,
            name: 'Return List',
            hasSubMenu: true,
            routerLink: 'pos/sales/return-list',
            icon: 'arrow_right',
          },
        ],
      },
      {
        id: 300,
        name: 'Customer',
        hasSubMenu: true,
        routerLink: null,
        icon: 'people',
        subMenus: [
          {
            id: 9,
            name: 'Customer List',
            hasSubMenu: true,
            routerLink: 'pos/customer/customer-list',
            icon: 'arrow_right',
          },
          {
            id: 10,
            name: 'Add Customer',
            hasSubMenu: true,
            routerLink: 'pos/customer/add-customer',
            icon: 'arrow_right',
          },
          {
            id: 11,
            name: 'Membership Cards',
            hasSubMenu: true,
            routerLink: 'pos/customer/membership-card-list',
            icon: 'arrow_right',
          },
        ],
      },
      {
        id: 400,
        name: 'Supplier',
        hasSubMenu: true,
        routerLink: null,
        icon: 'local_shipping',
        subMenus: [
          {
            id: 11,
            name: 'Supplier List',
            hasSubMenu: true,
            routerLink: 'pos/supplier/supplier-list',
            icon: 'arrow_right',
          },
          {
            id: 12,
            name: 'Add Supplier',
            hasSubMenu: true,
            routerLink: 'pos/supplier/add-supplier',
            icon: 'arrow_right',
          },
        ],
      },
      {
        id: 500,
        name: 'Purchase',
        hasSubMenu: true,
        routerLink: null,
        icon: 'shopping_bag',
        subMenus: [
          {
            id: 13,
            name: 'Purchase List',
            hasSubMenu: true,
            routerLink: 'pos/purchase/purchase-list',
            icon: 'arrow_right',
          },
          {
            id: 14,
            name: 'Add Purchase',
            hasSubMenu: true,
            routerLink: 'pos/purchase/add-purchase',
            icon: 'arrow_right',
          },
          {
            id: 15,
            name: 'Purchase Return',
            hasSubMenu: true,
            routerLink: 'pos/purchase/purchase-return-list',
            icon: 'arrow_right',
          },
        ],
      },

      {
        id: 700,
        name: 'Reports',
        hasSubMenu: true,
        routerLink: null,
        icon: 'assessment',
        subMenus: [

          {
            id: 24,
            name: 'Daily Sale Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/daily-sale',
            icon: 'arrow_right',
          },
          {
            id: 25,
            name: 'User Wise Sale Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/user-wise-sale',
            icon: 'arrow_right',
          },
          {
            id: 42,
            name: 'Branch Wise Sale Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/branch-wise-sale',
            icon: 'arrow_right',
          },
          {
            id: 26,
            name: 'Product Profit Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/product-profit',
            icon: 'arrow_right',
          },
          {
            id: 27,
            name: 'Top Selling Products',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/top-selling-products',
            icon: 'arrow_right',
          },
          {
            id: 28,
            name: 'Slow Selling Products',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/slow-selling-products',
            icon: 'arrow_right',
          },
          {
            id: 29,
            name: 'Purchase vs Sale',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/purchase-vs-sale',
            icon: 'arrow_right',
          },
          {
            id: 30,
            name: 'Customer Due Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/customer-due',
            icon: 'arrow_right',
          },
          {
            id: 31,
            name: 'Expense Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/expense',
            icon: 'arrow_right',
          },
          {
            id: 32,
            name: 'Inventory Valuation',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/inventory-valuation',
            icon: 'arrow_right',
          },
          {
            id: 33,
            name: 'Stock Value Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/stock-value',
            icon: 'arrow_right',
          },
          {
            id: 34,
            name: 'Purchase Payment Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/purchase-payment',
            icon: 'arrow_right',
          },
          {
            id: 35,
            name: 'Sell Payment Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/sell-payment',
            icon: 'arrow_right',
          },
          {
            id: 36,
            name: 'Product Sell Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/product-sell',
            icon: 'arrow_right',
          },
          {
            id: 37,
            name: 'Product Purchase Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/product-purchase',
            icon: 'arrow_right',
          },
          {
            id: 38,
            name: 'Activity Log',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/activity-log',
            icon: 'arrow_right',
          },

        ],
      },
      {
        id: 800,
        name: 'Stock Management',
        hasSubMenu: true,
        routerLink: null,
        icon: 'inventory',
        subMenus: [
          {
            id: 43,
            name: 'Stock Adjustment List',
            hasSubMenu: true,
            routerLink: 'pos/stock-adjustment/list',
            icon: 'arrow_right',
          },
          {
            id: 44,
            name: 'Add Stock Adjustment',
            hasSubMenu: true,
            routerLink: 'pos/stock-adjustment/add',
            icon: 'arrow_right',
          },
          {
            id: 45,
            name: 'Product Damage / Wastage List',
            hasSubMenu: true,
            routerLink: 'pos/product-damage/list',
            icon: 'arrow_right',
          },
          {
            id: 46,
            name: 'Add Product Damage',
            hasSubMenu: true,
            routerLink: 'pos/product-damage/add',
            icon: 'arrow_right',
          },
          {
            id: 47,
            name: 'Price History',
            hasSubMenu: true,
            routerLink: 'pos/price-history',
            icon: 'arrow_right',
          },
        ],
      },
      // {
      //   id: 900,
      //   name: 'Branch Management',
      //   hasSubMenu: true,
      //   routerLink: null,
      //   icon: 'store',
      //   subMenus: [
      //     {
      //       id: 35,
      //       name: 'Branch List',
      //       hasSubMenu: true,
      //       routerLink: 'pos/branch-management/list',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 36,
      //       name: 'Add Branch',
      //       hasSubMenu: true,
      //       routerLink: 'pos/branch-management/add',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 37,
      //       name: 'Branch Inventory',
      //       hasSubMenu: true,
      //       routerLink: 'pos/branch-inventory/list',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 38,
      //       name: 'Transfer Request',
      //       hasSubMenu: true,
      //       routerLink: 'pos/transfer-request/list',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 39,
      //       name: 'Central Dashboard',
      //       hasSubMenu: true,
      //       routerLink: 'pos/central-dashboard',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 40,
      //       name: 'Central Product List',
      //       hasSubMenu: true,
      //       routerLink: 'pos/central-product/list',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 41,
      //       name: 'Branch Access Management',
      //       hasSubMenu: true,
      //       routerLink: 'pos/branch-access/management',
      //       icon: 'arrow_right',
      //     },
      //   ],
      // },
      {
        id: 34,
        name: 'Printer Settings',
        hasSubMenu: true,
        routerLink: 'pos/settings/printer-settings',
        icon: 'print',
      },
      {
        id: 35,
        name: 'Tax & VAT Settings',
        hasSubMenu: true,
        routerLink: 'pos/settings/tax-vat-settings',
        icon: 'receipt',
      },
      {
        id: 36,
        name: 'Point Settings',
        hasSubMenu: true,
        routerLink: 'pos/settings/point-settings',
        icon: 'stars',
      },
    ],
  },
  {
    id: 10,
    name: 'Admin Control',
    hasSubMenu: false,
    routerLink: 'admin',
    icon: 'admin_panel_settings',
    subMenus: [],
  },
  // {
  //   id: 124,
  //   name: 'Blog Area',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'rss_feed',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'Blog',
  //       hasSubMenu: true,
  //       routerLink: 'blog/all-blog',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Blog Comment',
  //       hasSubMenu: true,
  //       routerLink: 'blog/all-comment',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 1255,
  //   name: 'All Trash',
  //   hasSubMenu: false,
  //   routerLink: 'trash',
  //   icon: 'auto_delete',
  //
  //   subMenus: [],
  // },

  // {
  //   id: 109,
  //   name: 'Support',
  //   hasSubMenu: false,
  //   routerLink: 'support',
  //   icon: 'help_center',
  //   subMenus: [],
  // },

  // {
  //   id: 12,
  //   name: 'Tutorials',
  //   hasSubMenu: false,
  //   routerLink: 'tutorial',
  //   icon: 'smart_display',
  //
  //   subMenus: [],
  // },

  // {
  //   id: 122,
  //   name: 'New Release',
  //   hasSubMenu: false,
  //   routerLink: 'new-release-report',
  //   icon: 'verified',
  //   subMenus: [],
  // },

  // {
  //   id: 123,
  //   name: 'Login Device',
  //   hasSubMenu: false,
  //   routerLink: 'login-all-device',
  //   icon: 'login',
  //
  //   subMenus: [],
  // },

  {
    id: 11,
    name: 'Profile',
    hasSubMenu: false,
    routerLink: 'profile',
    icon: 'person',

    subMenus: [],
  },

];

//Super Counter Menu
export const ALL_MENUS1: AdminMenu[] = [
  {
    id: 0,
    name: 'Dashboard',
    hasSubMenu: false,
    routerLink: 'dashboard',
    icon: 'space_dashboard',
    subMenus: [],
  },
  {
    id: 1,
    name: 'Orders',
    hasSubMenu: false,
    routerLink: 'order/all-order',
    icon: 'reorder',
    subMenus: [],
  },
  // {
  //   id: 1,
  //   name: 'Incomplete Orders',
  //   hasSubMenu: false,
  //   routerLink: 'order/all-incomplete-order',
  //   icon: 'reorder',
  //   subMenus: [],
  // },
  {
    id: 2,
    name: 'Products',
    hasSubMenu: false,
    routerLink: 'product/all-product',
    icon: 'inventory_2',
    subMenus: [],
  },
  // {
  //   id: 3,
  //   name: 'Settings',
  //   hasSubMenu: false,
  //   routerLink: 'settings/all-settings',
  //   icon: 'settings',
  //   subMenus: [],
  // },
  // {
  //   id: 4,
  //   name: 'Customization',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'tune',
  //   subMenus: [
  //     {
  //       id: 2,
  //       name: 'Carousel',
  //       hasSubMenu: true,
  //       routerLink: 'customization/all-carousel',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'Banner',
  //       hasSubMenu: true,
  //       routerLink: 'customization/all-banner',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 4,
  //       name: 'PopUp',
  //       hasSubMenu: true,
  //       routerLink: 'customization/all-popup',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 5,
  //       name: 'Website Information',
  //       hasSubMenu: true,
  //       routerLink: 'customization/website-information',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 6,
  //       name: 'Theme View',
  //       hasSubMenu: true,
  //       routerLink: 'customization/theme-view',
  //       icon: 'arrow_right',
  //     },
  //     // {
  //     //   id: 7,
  //     //   name: 'Themes',
  //     //   hasSubMenu: false,
  //     //   routerLink: 'customization/themes',
  //     //   icon: 'arrow_right',
  //     // },
  //     // {
  //     //   id: 8,
  //     //   name: 'Page View',
  //     //   hasSubMenu: true,
  //     //   routerLink: 'customization/page-view',
  //     //   icon: 'arrow_right',
  //     // },
  //   ],
  // },
  // {
  //   id: 5,
  //   name: 'Catalog',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'category',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'Categories',
  //       hasSubMenu: true,
  //       routerLink: 'catalog/all-category',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: ' Sub Categories',
  //       hasSubMenu: true,
  //       routerLink: 'catalog/all-sub-category',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: ' Child Categories',
  //       hasSubMenu: true,
  //       routerLink: 'catalog/all-child-category',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 4,
  //       name: 'Brand',
  //       hasSubMenu: true,
  //       routerLink: 'catalog/all-brand',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 6,
  //       name: 'Tags',
  //       hasSubMenu: true,
  //       routerLink: 'catalog/all-tag',
  //       icon: 'arrow_right',
  //     },
  //     // {
  //     //   id: 7,
  //     //   name: 'Skin Type',
  //     //   hasSubMenu: true,
  //     //   routerLink: 'catalog/all-skin-type',
  //     //   icon: 'arrow_right',
  //     // },
  //     // {
  //     //   id: 8,
  //     //   name: 'Skin Concern',
  //     //   hasSubMenu: true,
  //     //   routerLink: 'catalog/all-skin-concern',
  //     //   icon: 'arrow_right',
  //     // },
  //   ],
  // },
  // {
  //   id: 577,
  //   name: 'Landing page',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'web',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'Customizable Landing page',
  //       hasSubMenu: true,
  //       routerLink: 'landing-page/all-customizable-landing-page',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Ready Landing page',
  //       hasSubMenu: true,
  //       routerLink: 'landing-page/all-fixed-landing-page',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Ready Landing page2',
  //       hasSubMenu: true,
  //       routerLink: 'landing-page/all-ready-landing-page',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 6,
  //   name: 'Review',
  //   hasSubMenu: false,
  //   routerLink: 'review',
  //   icon: 'reviews',
  //   subMenus: [],
  // },
  //
  // {
  //   id: 7,
  //   name: 'Customer',
  //   hasSubMenu: false,
  //   routerLink: 'users/all-users',
  //   icon: 'group',
  //   subMenus: [],
  // },
  // {
  //   id: 77,
  //   name: 'Coupon',
  //   hasSubMenu: false,
  //   routerLink: 'coupon/all-coupon',
  //   icon: 'payments',
  //   subMenus: [],
  // },
  //
  // {
  //   id: 8,
  //   name: 'Gallery',
  //   hasSubMenu: false,
  //   routerLink: 'my-gallery',
  //   icon: 'insert_photo',
  //   subMenus: []
  // },
  // {
  //   id: 9,
  //   name: 'Additional Pages',
  //   hasSubMenu: false,
  //   routerLink: 'additional-pages/page-list',
  //   icon: 'pages',
  //   subMenus: [],
  // },
  // {
  //   id: 222,
  //   name: 'Seo Pages',
  //   hasSubMenu: false,
  //   routerLink: 'seo-page/all-seo-page',
  //   icon: 'traffic',
  //   subMenus: [],
  // },

  // {
  //   id: 117,
  //   name: 'Affiliate',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All affiliate',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/all-affiliate',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Affiliate product',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate-product/all-affiliate-product',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'Affiliate request',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/affiliate-request',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 4,
  //       name: 'All approved affiliate',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/all-approved-affiliate',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 5,
  //       name: 'All affiliate payment request',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/affiliate-payment-request',
  //       icon: 'arrow_right',
  //     },


  //   ],
  // },
  // {
  //   id: 19,
  //   name: 'Tutorial Page',
  //   hasSubMenu: false,
  //   routerLink: 'tutorial',
  //   icon: 'videocam',
  //   subMenus: [],
  // },
  // {
  //   id: 117,
  //   name: 'Subscription',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Subscription',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/all-subscription',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Subscription Report',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/subscription-report',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'My Subscription',
  //       hasSubMenu: true,
  //       routerLink: 'subscription/my-subscription',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 317,
  //   name: 'Manager',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Log Manager',
  //       hasSubMenu: true,
  //       routerLink: 'manager/all-log',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'All Trash Manager',
  //       hasSubMenu: true,
  //       routerLink: 'manager/all-trash',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 318,
  //   name: 'Expense',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Expense',
  //       hasSubMenu: true,
  //       routerLink: 'expense/all-expense',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 1,
  //       name: 'All category',
  //       hasSubMenu: true,
  //       routerLink: 'expense/all-category',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   id: 319,
  //   name: 'Income',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'trending_up',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Income',
  //       hasSubMenu: true,
  //       routerLink: 'income/all-income',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'All category',
  //       hasSubMenu: true,
  //       routerLink: 'income/all-category',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },

  // {
  //   id: 3218,
  //   name: 'User Notification',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All Notification',
  //       hasSubMenu: true,
  //       routerLink: 'fake-notification/all-notification',
  //       icon: 'arrow_right',
  //     },
  //   ],
  // },
  // {
  //   {
  //     id: 600,
  //     name: 'Accounts',
  //     hasSubMenu: true,
  //     routerLink: null,
  //     icon: 'account_balance',
  //     subMenus: [
  //       {
  //         id: 15,
  //         name: 'Bank Account List',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/bank-account-list',
  //         icon: 'arrow_right',
  //       },
  //       {
  //         id: 16,
  //         name: 'Add Bank Account',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/add-bank-account',
  //         icon: 'arrow_right',
  //       },
  //       {
  //         id: 17,
  //         name: 'Cash Transaction List',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/cash-transaction-list',
  //         icon: 'arrow_right',
  //       },
  //       {
  //         id: 18,
  //         name: 'Add Cash Transaction',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/add-cash-transaction',
  //         icon: 'arrow_right',
  //       },
  //       {
  //         id: 19,
  //         name: 'Accounts Ledger',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/accounts-ledger',
  //         icon: 'arrow_right',
  //       },
  //       {
  //         id: 20,
  //         name: 'Day Close',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/day-close',
  //         icon: 'arrow_right',
  //       },
  //
  //       {
  //         id: 21,
  //         name: 'Balance Sheet',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/reports/balance-sheet',
  //         icon: 'arrow_right',
  //       },
  //       {
  //         id: 22,
  //         name: 'Profit & Loss',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/reports/profit-loss',
  //         icon: 'arrow_right',
  //       },
  //       {
  //         id: 23,
  //         name: 'Tax Report',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/reports/tax-report',
  //         icon: 'arrow_right',
  //       },
  //       {
  //         id: 39,
  //         name: 'Sales Record',
  //         hasSubMenu: true,
  //         routerLink: 'pos/accounts/reports/sales-record',
  //         icon: 'arrow_right',
  //       },
  //     ],
  //   },
  {
    id: 13,
    name: 'Pos',
    hasSubMenu: true,
    routerLink: null,
    icon: 'point_of_sale',
    subMenus: [
      {
        id: 99,
        name: 'POS Dashboard',
        hasSubMenu: true,
        routerLink: 'pos/dashboard',
        icon: 'dashboard',
      },
      {
        id: 100,
        name: 'Repair',
        hasSubMenu: true,
        routerLink: null,
        icon: 'build',
        subMenus: [
          {
            id: 1,
            name: 'Repair List',
            hasSubMenu: true,
            routerLink: 'repair/repair-list',
            icon: 'arrow_right',
          },
          {
            id: 2,
            name: 'Add Repair',
            hasSubMenu: true,
            routerLink: 'repair/add-repair',
            icon: 'arrow_right',
          },
          {
            id: 3,
            name: 'Model',
            hasSubMenu: true,
            routerLink: 'repair/model-list',
            icon: 'arrow_right',
          },
          {
            id: 4,
            name: 'Problem',
            hasSubMenu: true,
            routerLink: 'repair/problem-list',
            icon: 'arrow_right',
          },
          {
            id: 5,
            name: 'Technician Report',
            hasSubMenu: true,
            routerLink: 'repair/technician-report',
            icon: 'arrow_right',
          },
          {
            id: 6,
            name: 'Technician List',
            hasSubMenu: true,
            routerLink: 'repair/technician-list',
            icon: 'arrow_right',
          },
          {
            id: 7,
            name: 'Add Technician',
            hasSubMenu: true,
            routerLink: 'repair/add-technician',
            icon: 'arrow_right',
          },
        ],
      },
      {
        id: 200,
        name: 'Sales',
        hasSubMenu: true,
        routerLink: null,
        icon: 'shopping_cart',
        subMenus: [
          {
            id: 5,
            name: 'Sales List',
            hasSubMenu: true,
            routerLink: 'pos/sales/sale-list',
            icon: 'arrow_right',
          },
          {
            id: 6,
            name: 'New Sale',
            hasSubMenu: true,
            routerLink: 'pos/sales/new-sales',
            icon: 'arrow_right',
          },
          {
            id: 7,
            name: 'Sales Return',
            hasSubMenu: true,
            routerLink: 'pos/sales/new-sales-return',
            icon: 'arrow_right',
          },
          {
            id: 8,
            name: 'Return List',
            hasSubMenu: true,
            routerLink: 'pos/sales/return-list',
            icon: 'arrow_right',
          },
        ],
      },
      {
        id: 300,
        name: 'Customer',
        hasSubMenu: true,
        routerLink: null,
        icon: 'people',
        subMenus: [
          {
            id: 9,
            name: 'Customer List',
            hasSubMenu: true,
            routerLink: 'pos/customer/customer-list',
            icon: 'arrow_right',
          },
          {
            id: 10,
            name: 'Add Customer',
            hasSubMenu: true,
            routerLink: 'pos/customer/add-customer',
            icon: 'arrow_right',
          },
          {
            id: 11,
            name: 'Membership Cards',
            hasSubMenu: true,
            routerLink: 'pos/customer/membership-card-list',
            icon: 'arrow_right',
          },
        ],
      },
      {
        id: 400,
        name: 'Supplier',
        hasSubMenu: true,
        routerLink: null,
        icon: 'local_shipping',
        subMenus: [
          {
            id: 11,
            name: 'Supplier List',
            hasSubMenu: true,
            routerLink: 'pos/supplier/supplier-list',
            icon: 'arrow_right',
          },
          {
            id: 12,
            name: 'Add Supplier',
            hasSubMenu: true,
            routerLink: 'pos/supplier/add-supplier',
            icon: 'arrow_right',
          },
        ],
      },
      {
        id: 500,
        name: 'Purchase',
        hasSubMenu: true,
        routerLink: null,
        icon: 'shopping_bag',
        subMenus: [
          {
            id: 13,
            name: 'Purchase List',
            hasSubMenu: true,
            routerLink: 'pos/purchase/purchase-list',
            icon: 'arrow_right',
          },
          {
            id: 14,
            name: 'Add Purchase',
            hasSubMenu: true,
            routerLink: 'pos/purchase/add-purchase',
            icon: 'arrow_right',
          },
          {
            id: 15,
            name: 'Purchase Return',
            hasSubMenu: true,
            routerLink: 'pos/purchase/purchase-return-list',
            icon: 'arrow_right',
          },
        ],
      },

      {
        id: 700,
        name: 'Reports',
        hasSubMenu: true,
        routerLink: null,
        icon: 'assessment',
        subMenus: [

          {
            id: 24,
            name: 'Daily Sale Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/daily-sale',
            icon: 'arrow_right',
          },
          {
            id: 25,
            name: 'User Wise Sale Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/user-wise-sale',
            icon: 'arrow_right',
          },
          {
            id: 42,
            name: 'Branch Wise Sale Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/branch-wise-sale',
            icon: 'arrow_right',
          },
          {
            id: 26,
            name: 'Product Profit Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/product-profit',
            icon: 'arrow_right',
          },
          {
            id: 27,
            name: 'Top Selling Products',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/top-selling-products',
            icon: 'arrow_right',
          },
          {
            id: 28,
            name: 'Slow Selling Products',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/slow-selling-products',
            icon: 'arrow_right',
          },
          {
            id: 29,
            name: 'Purchase vs Sale',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/purchase-vs-sale',
            icon: 'arrow_right',
          },
          {
            id: 30,
            name: 'Customer Due Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/customer-due',
            icon: 'arrow_right',
          },
          {
            id: 31,
            name: 'Expense Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/expense',
            icon: 'arrow_right',
          },
          {
            id: 32,
            name: 'Inventory Valuation',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/inventory-valuation',
            icon: 'arrow_right',
          },
          {
            id: 33,
            name: 'Stock Value Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/stock-value',
            icon: 'arrow_right',
          },
          {
            id: 34,
            name: 'Purchase Payment Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/purchase-payment',
            icon: 'arrow_right',
          },
          {
            id: 35,
            name: 'Sell Payment Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/sell-payment',
            icon: 'arrow_right',
          },
          {
            id: 36,
            name: 'Product Sell Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/product-sell',
            icon: 'arrow_right',
          },
          {
            id: 37,
            name: 'Product Purchase Report',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/product-purchase',
            icon: 'arrow_right',
          },
          {
            id: 38,
            name: 'Activity Log',
            hasSubMenu: true,
            routerLink: 'pos/accounts/reports/activity-log',
            icon: 'arrow_right',
          },

        ],
      },
      {
        id: 800,
        name: 'Stock Management',
        hasSubMenu: true,
        routerLink: null,
        icon: 'inventory',
        subMenus: [
          {
            id: 43,
            name: 'Stock Adjustment List',
            hasSubMenu: true,
            routerLink: 'pos/stock-adjustment/list',
            icon: 'arrow_right',
          },
          {
            id: 44,
            name: 'Add Stock Adjustment',
            hasSubMenu: true,
            routerLink: 'pos/stock-adjustment/add',
            icon: 'arrow_right',
          },
          {
            id: 45,
            name: 'Product Damage / Wastage List',
            hasSubMenu: true,
            routerLink: 'pos/product-damage/list',
            icon: 'arrow_right',
          },
          {
            id: 46,
            name: 'Add Product Damage',
            hasSubMenu: true,
            routerLink: 'pos/product-damage/add',
            icon: 'arrow_right',
          },
          {
            id: 47,
            name: 'Price History',
            hasSubMenu: true,
            routerLink: 'pos/price-history',
            icon: 'arrow_right',
          },
        ],
      },
      // {
      //   id: 900,
      //   name: 'Branch Management',
      //   hasSubMenu: true,
      //   routerLink: null,
      //   icon: 'store',
      //   subMenus: [
      //     {
      //       id: 35,
      //       name: 'Branch List',
      //       hasSubMenu: true,
      //       routerLink: 'pos/branch-management/list',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 36,
      //       name: 'Add Branch',
      //       hasSubMenu: true,
      //       routerLink: 'pos/branch-management/add',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 37,
      //       name: 'Branch Inventory',
      //       hasSubMenu: true,
      //       routerLink: 'pos/branch-inventory/list',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 38,
      //       name: 'Transfer Request',
      //       hasSubMenu: true,
      //       routerLink: 'pos/transfer-request/list',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 39,
      //       name: 'Central Dashboard',
      //       hasSubMenu: true,
      //       routerLink: 'pos/central-dashboard',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 40,
      //       name: 'Central Product List',
      //       hasSubMenu: true,
      //       routerLink: 'pos/central-product/list',
      //       icon: 'arrow_right',
      //     },
      //     {
      //       id: 41,
      //       name: 'Branch Access Management',
      //       hasSubMenu: true,
      //       routerLink: 'pos/branch-access/management',
      //       icon: 'arrow_right',
      //     },
      //   ],
      // },
      {
        id: 34,
        name: 'Printer Settings',
        hasSubMenu: true,
        routerLink: 'pos/settings/printer-settings',
        icon: 'print',
      },
      {
        id: 35,
        name: 'Tax & VAT Settings',
        hasSubMenu: true,
        routerLink: 'pos/settings/tax-vat-settings',
        icon: 'receipt',
      },
      {
        id: 36,
        name: 'Point Settings',
        hasSubMenu: true,
        routerLink: 'pos/settings/point-settings',
        icon: 'stars',
      },
    ],
  },
  {
    id: 10,
    name: 'Admin Control',
    hasSubMenu: false,
    routerLink: 'admin',
    icon: 'admin_panel_settings',
    subMenus: [],
  },
  {
    id: 124,
    name: 'Blog Area',
    hasSubMenu: true,
    routerLink: null,
    icon: 'rss_feed',
    subMenus: [
      {
        id: 1,
        name: 'Blog',
        hasSubMenu: true,
        routerLink: 'blog/all-blog',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: 'Blog Comment',
        hasSubMenu: true,
        routerLink: 'blog/all-comment',
        icon: 'arrow_right',
      },
    ],
  },
  // {
  //   id: 1255,
  //   name: 'All Trash',
  //   hasSubMenu: false,
  //   routerLink: 'trash',
  //   icon: 'auto_delete',
  //
  //   subMenus: [],
  // },

  {
    id: 109,
    name: 'Support',
    hasSubMenu: false,
    routerLink: 'support',
    icon: 'help_center',
    subMenus: [],
  },

  {
    id: 12,
    name: 'Tutorials',
    hasSubMenu: false,
    routerLink: 'tutorial',
    icon: 'smart_display',

    subMenus: [],
  },

  // {
  //   id: 122,
  //   name: 'New Release',
  //   hasSubMenu: false,
  //   routerLink: 'new-release-report',
  //   icon: 'verified',
  //   subMenus: [],
  // },

  // {
  //   id: 123,
  //   name: 'Login Device',
  //   hasSubMenu: false,
  //   routerLink: 'login-all-device',
  //   icon: 'login',
  //
  //   subMenus: [],
  // },

  {
    id: 11,
    name: 'Profile',
    hasSubMenu: false,
    routerLink: 'profile',
    icon: 'person',

    subMenus: [],
  },


];

//Manager Menu
export const MANAGER_MENU: AdminMenu[] = [
  {
    id: 0,
    name: 'Dashboard',
    hasSubMenu: false,
    routerLink: 'dashboard',
    icon: 'space_dashboard',
    subMenus: [],
  },
  // {
  //   id: 1,
  //   name: 'Orders',
  //   hasSubMenu: false,
  //   routerLink: 'order/all-order',
  //   icon: 'reorder',
  //   subMenus: [],
  // },
  {
    id: 2,
    name: 'Products',
    hasSubMenu: false,
    routerLink: 'product/all-product',
    icon: 'inventory_2',
    subMenus: [],
  },
  {
    id: 3,
    name: 'Settings',
    hasSubMenu: false,
    routerLink: 'settings/all-settings',
    icon: 'settings',
    subMenus: [],
  },
  // {
  //   id: 4,
  //   name: 'Customization',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'tune',
  //   subMenus: [
  //     {
  //       id: 2,
  //       name: 'Carousel',
  //       hasSubMenu: true,
  //       routerLink: 'customization/all-carousel',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'Banner',
  //       hasSubMenu: true,
  //       routerLink: 'customization/all-banner',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 4,
  //       name: 'PopUp',
  //       hasSubMenu: true,
  //       routerLink: 'customization/all-popup',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 5,
  //       name: 'Website Information',
  //       hasSubMenu: true,
  //       routerLink: 'customization/website-information',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 6,
  //       name: 'Theme View',
  //       hasSubMenu: true,
  //       routerLink: 'customization/theme-view',
  //       icon: 'arrow_right',
  //     },
  //     // {
  //     //   id: 6,
  //     //   name: 'Page View',
  //     //   hasSubMenu: true,
  //     //   routerLink: 'customization/page-view',
  //     //   icon: 'arrow_right',
  //     // },
  //   ],
  // },
  {
    id: 5,
    name: 'Catalog',
    hasSubMenu: true,
    routerLink: null,
    icon: 'category',
    subMenus: [
      {
        id: 1,
        name: 'Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-category',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: ' Sub Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-sub-category',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: ' Child Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-child-category',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'Brand',
        hasSubMenu: true,
        routerLink: 'catalog/all-brand',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Tags',
        hasSubMenu: true,
        routerLink: 'catalog/all-tag',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 577,
    name: 'Landing page',
    hasSubMenu: false,
    routerLink: 'landing-page/all-landing',
    icon: 'web',
    subMenus: [],
  },
  {
    id: 6,
    name: 'Review',
    hasSubMenu: false,
    routerLink: 'review',
    icon: 'reviews',
    subMenus: [],
  },
  {
    id: 7,
    name: 'Customer',
    hasSubMenu: false,
    routerLink: 'users/all-users',
    icon: 'group',
    subMenus: [],
  },
  {
    id: 8,
    name: 'Gallery',
    hasSubMenu: false,
    routerLink: 'my-gallery',
    icon: 'insert_photo',
    subMenus: []
  },
  {
    id: 9,
    name: 'Additional Pages',
    hasSubMenu: false,
    routerLink: 'additional-pages/page-list',
    icon: 'pages',
    subMenus: [],
  },
  {
    id: 222,
    name: 'Seo Pages',
    hasSubMenu: false,
    routerLink: 'seo-page/all-seo-page',
    icon: 'traffic',
    subMenus: [],
  },
  // {
  //   id: 117,
  //   name: 'Affiliate',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All affiliate',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/all-affiliate',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Affiliate product',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate-product/all-affiliate-product',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'Affiliate request',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/affiliate-request',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 4,
  //       name: 'All approved affiliate',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/all-approved-affiliate',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 5,
  //       name: 'All affiliate payment request',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/affiliate-payment-request',
  //       icon: 'arrow_right',
  //     },


  //   ],
  // },
  {
    id: 11,
    name: 'Profile',
    hasSubMenu: false,
    routerLink: 'profile',
    icon: 'person',

    subMenus: [],
  },
  {
    id: 13,
    name: 'POS',
    hasSubMenu: true,
    routerLink: null,
    icon: 'point_of_sale',
    subMenus: [
      {
        id: 1,
        name: 'Repair List',
        hasSubMenu: true,
        routerLink: 'repair/repair-list',
        icon: 'arrow_right',
      },
      // {
      //   id: 2,
      //   name: 'Brand',
      //   hasSubMenu: true,
      //   routerLink: 'repair/brand-list',
      //   icon: 'arrow_right',
      // },
      {
        id: 3,
        name: 'Model',
        hasSubMenu: true,
        routerLink: 'repair/model-list',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'Problem',
        hasSubMenu: true,
        routerLink: 'repair/problem-list',
        icon: 'arrow_right',
      },
      {
        id: 5,
        name: 'Sales List',
        hasSubMenu: true,
        routerLink: 'pos/sales/sale-list',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'New Sale',
        hasSubMenu: true,
        routerLink: 'pos/sales/new-sales',
        icon: 'arrow_right',
      },
      {
        id: 7,
        name: 'Customer List',
        hasSubMenu: true,
        routerLink: 'pos/customer/customer-list',
        icon: 'arrow_right',
      },
      {
        id: 8,
        name: 'Add Customer',
        hasSubMenu: true,
        routerLink: 'pos/customer/add-customer',
        icon: 'arrow_right',
      },
      {
        id: 9,
        name: 'Membership Cards',
        hasSubMenu: true,
        routerLink: 'pos/customer/membership-card-list',
        icon: 'arrow_right',
      },
      {
        id: 9,
        name: 'Supplier List',
        hasSubMenu: true,
        routerLink: 'pos/supplier/supplier-list',
        icon: 'arrow_right',
      },
      {
        id: 10,
        name: 'Add Supplier',
        hasSubMenu: true,
        routerLink: 'pos/supplier/add-supplier',
        icon: 'arrow_right',
      },
      {
        id: 11,
        name: 'Purchase List',
        hasSubMenu: true,
        routerLink: 'pos/purchase/purchase-list',
        icon: 'arrow_right',
      },
      {
        id: 12,
        name: 'Add Purchase',
        hasSubMenu: true,
        routerLink: 'pos/purchase/add-purchase',
        icon: 'arrow_right',
      },
      {
        id: 13,
        name: 'Purchase Return',
        hasSubMenu: true,
        routerLink: 'pos/purchase/purchase-return-list',
        icon: 'arrow_right',
      },
      {
        id: 15,
        name: 'Bank Account List',
        hasSubMenu: true,
        routerLink: 'pos/accounts/bank-account-list',
        icon: 'arrow_right',
      },
      {
        id: 16,
        name: 'Add Bank Account',
        hasSubMenu: true,
        routerLink: 'pos/accounts/add-bank-account',
        icon: 'arrow_right',
      },
      {
        id: 17,
        name: 'Cash Transaction List',
        hasSubMenu: true,
        routerLink: 'pos/accounts/cash-transaction-list',
        icon: 'arrow_right',
      },
      {
        id: 18,
        name: 'Add Cash Transaction',
        hasSubMenu: true,
        routerLink: 'pos/accounts/add-cash-transaction',
        icon: 'arrow_right',
      },
      {
        id: 19,
        name: 'Accounts Ledger',
        hasSubMenu: true,
        routerLink: 'pos/accounts/accounts-ledger',
        icon: 'arrow_right',
      },
      {
        id: 20,
        name: 'Day Close',
        hasSubMenu: true,
        routerLink: 'pos/accounts/day-close',
        icon: 'arrow_right',
      },
      {
        id: 21,
        name: 'Balance Sheet',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/balance-sheet',
        icon: 'arrow_right',
      },
      {
        id: 22,
        name: 'Profit & Loss',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/profit-loss',
        icon: 'arrow_right',
      },
      {
        id: 23,
        name: 'Tax Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/tax-report',
        icon: 'arrow_right',
      },
      {
        id: 24,
        name: 'Daily Sale Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/daily-sale',
        icon: 'arrow_right',
      },
      {
        id: 25,
        name: 'User Wise Sale Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/user-wise-sale',
        icon: 'arrow_right',
      },
      {
        id: 26,
        name: 'Product Profit Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/product-profit',
        icon: 'arrow_right',
      },
      {
        id: 27,
        name: 'Top Selling Products',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/top-selling-products',
        icon: 'arrow_right',
      },
      {
        id: 28,
        name: 'Slow Selling Products',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/slow-selling-products',
        icon: 'arrow_right',
      },
      {
        id: 29,
        name: 'Purchase vs Sale',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/purchase-vs-sale',
        icon: 'arrow_right',
      },
      {
        id: 30,
        name: 'Customer Due Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/customer-due',
        icon: 'arrow_right',
      },
      {
        id: 31,
        name: 'Expense Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/expense',
        icon: 'arrow_right',
      },
      {
        id: 32,
        name: 'Inventory Valuation',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/inventory-valuation',
        icon: 'arrow_right',
      },
      {
        id: 33,
        name: 'Stock Value Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/stock-value',
        icon: 'arrow_right',
      },
      {
        id: 34,
        name: 'Purchase Payment Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/purchase-payment',
        icon: 'arrow_right',
      },
      {
        id: 35,
        name: 'Sell Payment Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/sell-payment',
        icon: 'arrow_right',
      },
      {
        id: 36,
        name: 'Product Sell Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/product-sell',
        icon: 'arrow_right',
      },
      {
        id: 37,
        name: 'Product Purchase Report',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/product-purchase',
        icon: 'arrow_right',
      },
      {
        id: 38,
        name: 'Activity Log',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/activity-log',
        icon: 'arrow_right',
      },
      {
        id: 39,
        name: 'Sales Record',
        hasSubMenu: true,
        routerLink: 'pos/accounts/reports/sales-record',
        icon: 'arrow_right',
      },
    ],
  },

];

export const EDITOR_MENU: AdminMenu[] = [
  {
    id: 0,
    name: 'Dashboard',
    hasSubMenu: false,
    routerLink: 'dashboard',
    icon: 'space_dashboard',
    subMenus: [],
  },
  {
    id: 1,
    name: 'Orders',
    hasSubMenu: false,
    routerLink: 'order/all-order',
    icon: 'reorder',
    subMenus: [],
  },
  {
    id: 2,
    name: 'Products',
    hasSubMenu: false,
    routerLink: 'product/all-product',
    icon: 'inventory_2',
    subMenus: [],
  },
  {
    id: 3,
    name: 'Settings',
    hasSubMenu: false,
    routerLink: 'settings/all-settings',
    icon: 'settings',
    subMenus: [],
  },
  {
    id: 4,
    name: 'Customization',
    hasSubMenu: true,
    routerLink: null,
    icon: 'tune',
    subMenus: [
      {
        id: 2,
        name: 'Carousel',
        hasSubMenu: true,
        routerLink: 'customization/all-carousel',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: 'Banner',
        hasSubMenu: true,
        routerLink: 'customization/all-banner',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'PopUp',
        hasSubMenu: true,
        routerLink: 'customization/all-popup',
        icon: 'arrow_right',
      },
      {
        id: 5,
        name: 'Website Information',
        hasSubMenu: true,
        routerLink: 'customization/website-information',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Theme View',
        hasSubMenu: true,
        routerLink: 'customization/theme-view',
        icon: 'arrow_right',
      },
      // {
      //   id: 7,
      //   name: 'Themes',
      //   hasSubMenu: false,
      //   routerLink: 'customization/themes',
      //   icon: 'arrow_right',
      // },
      // {
      //   id: 8,
      //   name: 'Page View',
      //   hasSubMenu: true,
      //   routerLink: 'customization/page-view',
      //   icon: 'arrow_right',
      // },
    ],
  },
  {
    id: 5,
    name: 'Catalog',
    hasSubMenu: true,
    routerLink: null,
    icon: 'category',
    subMenus: [
      {
        id: 1,
        name: 'Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-category',
        icon: 'arrow_right',
      },
      {
        id: 2,
        name: ' Sub Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-sub-category',
        icon: 'arrow_right',
      },
      {
        id: 3,
        name: ' Child Categories',
        hasSubMenu: true,
        routerLink: 'catalog/all-child-category',
        icon: 'arrow_right',
      },
      {
        id: 4,
        name: 'Brand',
        hasSubMenu: true,
        routerLink: 'catalog/all-brand',
        icon: 'arrow_right',
      },
      {
        id: 6,
        name: 'Tags',
        hasSubMenu: true,
        routerLink: 'catalog/all-tag',
        icon: 'arrow_right',
      },
    ],
  },
  {
    id: 577,
    name: 'Landing page',
    hasSubMenu: false,
    routerLink: 'landing-page/all-landing',
    icon: 'web',
    subMenus: [],
  },
  {
    id: 6,
    name: 'Review',
    hasSubMenu: false,
    routerLink: 'review',
    icon: 'reviews',
    subMenus: [],
  },
  {
    id: 7,
    name: 'Customer',
    hasSubMenu: false,
    routerLink: 'users/all-users',
    icon: 'group',
    subMenus: [],
  },
  {
    id: 8,
    name: 'Gallery',
    hasSubMenu: false,
    routerLink: 'my-gallery',
    icon: 'insert_photo',
    subMenus: []
  },
  {
    id: 9,
    name: 'Additional Pages',
    hasSubMenu: false,
    routerLink: 'additional-pages/page-list',
    icon: 'pages',
    subMenus: [],
  },

  {
    id: 222,
    name: 'Seo Pages',
    hasSubMenu: false,
    routerLink: 'seo-page/all-seo-page',
    icon: 'traffic',
    subMenus: [],
  },

  // {
  //   id: 117,
  //   name: 'Affiliate',
  //   hasSubMenu: true,
  //   routerLink: null,
  //   icon: 'assessment',
  //   subMenus: [
  //     {
  //       id: 1,
  //       name: 'All affiliate',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/all-affiliate',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 2,
  //       name: 'Affiliate product',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate-product/all-affiliate-product',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 3,
  //       name: 'Affiliate request',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/affiliate-request',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 4,
  //       name: 'All approved affiliate',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/all-approved-affiliate',
  //       icon: 'arrow_right',
  //     },
  //     {
  //       id: 5,
  //       name: 'All affiliate payment request',
  //       hasSubMenu: true,
  //       routerLink: 'affiliate/affiliate-payment-request',
  //       icon: 'arrow_right',
  //     },


  //   ],
  // },

  {
    id: 11,
    name: 'Profile',
    hasSubMenu: false,
    routerLink: 'profile',
    icon: 'person',

    subMenus: [],
  },


];

// Filter menu items based on deployment type
// Hide Support (id: 109) and New Release (id: 122) when deploymentType is not 'default'
export const SUPER_ADMIN_MENU: AdminMenu[] = environment.deploymentType === 'default'
  ? ALL_MENUS
  : ALL_MENUS.filter(menu => menu.id !== 109 && menu.id !== 122);
